.equiv itemWheel.asm, static.address # 8b
.equiv dropItemsAtCommand.asm, static.address + 0x8 # 4b
.equiv rainbowKart8.asm, static.address + 0xC # 4b
.equiv freefly.asm, static.address + 0x10 # 8b
.equiv switchFOVAtCommand.asm, static.address + 0x18 # 4b
.equiv moonjump.asm, static.address + 0x1C # 4b
.equiv rapidfire.asm, static.address + 0x20 # 4b
.equiv aimbot.asm, static.address + 0x24 # 8b
.equiv dialogBoxTest.asm, static.address + 0x2C # ?b